# Generated by Django 4.2.5 on 2023-09-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_availablebookings_available_tables_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availablebookings",
            name="updated_on",
            field=models.DateTimeField(default=0),
        ),
    ]
