# Generated by Django 3.2.21 on 2023-09-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_availablebookings_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(max_length=30),
        ),
    ]
